global:
  scrape_interval: 10s

scrape_configs:
  # Obtiene las metricas que expone el otel-collector en el puerto del exporter prometheus
  - job_name: otel-collector
    static_configs:
      - targets: ["otel-collector:8889"]